version: '2'
services:
  solr:
    build: ./solr
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
      - /opt/docker-solr/myconfig
volumes:
  data: